Rails:
  Enabled: true

Rails/Delegate:
  Enabled: false

# inherit_gem:
#   rubocop-rails:
#     - config/rails.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'

Layout/MultilineMethodDefinitionBraceLayout:
  EnforcedStyle: same_line

Metrics/LineLength:
  Max: 110

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
  ExcludedMethods: ['describe', 'context', 'xdescribe', 'xcontext']

Layout/SpaceInsideBlockBraces:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
